config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    root to: 'formulas#index' # home page

    authenticated :user do
      root 'formulas#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show, :edit, :update]
  resources :formulas, except: :destroy

end

app/models/formula.rb
class Formula < ActiveRecord::Base
  after_initialize :set_defaults

  has_many :formulas_progress_steps
  has_many :progress_steps, -> { order(position: :asc) }, through: :formulas_progress_steps
  has_many :formulas_assets

  accepts_nested_attributes_for :formulas_progress_steps, reject_if: :reject_formula_progress_step #, allow_destroy: true
  accepts_nested_attributes_for :formulas_assets, reject_if: :reject_formula_asset #, allow_destroy: true

  validates :code, presence: true, uniqueness: true
  validates :priority, inclusion: { in: (1..3) }
  validate :comments_check_character_encoding

  scope :state, -> (state) { where state: state }
  scope :non_ascii_comments, -> { where("comments <> CONVERT(comments USING ASCII)") }

  state_machine :state, :initial => :open do

    event :complete do
      transition :open => :completed
    end

    event :archive do
      transition :open => :archived
    end

  end

  def self.state_options(with_all=false)
    state_machine.states.map{|s| [s.name, s.name] }
  end

  def reject_formula_progress_step(attributes)
    attributes[:completed] == 'false' &&
    attributes[:completed_on].blank? &&
    attributes[:comments].blank?
  end

  def reject_formula_asset(attributes)
    attributes[:asset].blank?
  end

  trigger.after(:insert) do
    destination_db = Rails.application.config.database_configuration()["#{Rails.env}_sync"]['database']

    <<-SQL
    thisTrigger: BEGIN
      IF (@TRIGGER_CHECKS_CHEMFIL1 = FALSE) THEN
        LEAVE thisTrigger;
      END IF;

      SET @TRIGGER_CHECKS_DIMACHEM = FALSE;
      INSERT INTO #{destination_db}.new_product_progress_data
        (`Product Code`, `Product Name`, `Priority`, `Status`, `Sr_Mgmt_Rev_BY`, `Start Date`, `Requested By`, `Customer`)
      VALUES
        (NEW.code, NEW.name, NEW.priority, NEW.state, NEW.reviewed_by, NEW.start_date, NEW.requested_by, NEW.customer);

      INSERT INTO #{destination_db}.new_product_progress_data_comments
        (`Product Code`, `Comments`)
      VALUES
        (NEW.code, NEW.comments);
    END thisTrigger
    SQL
  end

  trigger.after(:update) do
    destination_db = Rails.application.config.database_configuration()["#{Rails.env}_sync"]['database']

    <<-SQL
    thisTrigger: BEGIN
      IF (@TRIGGER_CHECKS_CHEMFIL1 = FALSE) THEN
        LEAVE thisTrigger;
      END IF;

      SET @TRIGGER_CHECKS_DIMACHEM = FALSE;
      UPDATE #{destination_db}.new_product_progress_data
        SET `Product Name` = NEW.name,
            `Priority` = NEW.priority,
            `Status` = NEW.state,
            `Sr_Mgmt_Rev_BY` = NEW.reviewed_by,
            `Start Date` = NEW.start_date,
            `Requested By` = NEW.requested_by,
            `Customer` = NEW.customer
      WHERE `Product Code` = OLD.code;

      UPDATE #{destination_db}.new_product_progress_data_comments
        SET `Comments` = NEW.comments
      WHERE `Product Code` = OLD.code;
    END thisTrigger
    SQL
  end

  trigger.after(:delete) do
    destination_db = Rails.application.config.database_configuration()["#{Rails.env}_sync"]['database']

    <<-SQL
    thisTrigger: BEGIN
      IF (@TRIGGER_CHECKS_CHEMFIL1 = FALSE) THEN
        LEAVE thisTrigger;
      END IF;

      SET @TRIGGER_CHECKS_DIMACHEM = FALSE;
      DELETE FROM #{destination_db}.new_product_progress_data_comments
      WHERE `Product Code` = OLD.code;

      DELETE FROM #{destination_db}.new_product_progress_data
      WHERE `Product Code` = OLD.code;
    END thisTrigger
    SQL
  end

  private

  def comments_check_character_encoding
    # NOTE: this is required to support MySql ODBC 3.51 for MEMO field
    comments.try(:encode!, 'us-ascii')
  rescue Encoding::UndefinedConversionError => e
    errors.add(:comments, "has invalid character encoding: #{e.message}")
  end

  def set_defaults
    self.priority ||= 3
  end
end

app/controllers/formulas_controller.rb
class FormulasController < ApplicationController
  before_action :set_formula, only: [:show, :edit, :update, :destroy]

  before_action only: [:index] do
    skip_policy_scope
    get_query('query_formulas')
  end

  # GET /formulas
  def index
    @search = Formula.ransack(@query)
    @search.build_sort({name: 'priority', dir: 'asc'}) if @search.sorts.blank?
    @search.state_eq = 'open' unless params_has_state_condition?

    @formulas = @search.result
  end

  # GET /formulas/1
  def show
    authorize @formula
    # build_progress_steps(@formula)
  end

  # GET /formulas/new
  def new
    authorize Formula
    @state_select_options = Formula.state_options
    @details_title = 'New Formula'
    @default_collapse_state = 'in'
    @formula = Formula.new
    @formula.formulas_assets.build
    build_progress_steps(@formula)
  end

  # GET /formulas/1/edit
  def edit
    authorize @formula
    @state_select_options = Formula.state_options
    @details_title = @formula.name
    @formula.formulas_assets.build
    build_progress_steps(@formula)
  end

  # POST /formulas
  def create
    @formula = Formula.new(formula_params)
    authorize @formula
    build_multiple_assets

    if @formula.save
      redirect_to @formula, notice: 'Formula was successfully created.'
    else
      @state_select_options = Formula.state_options
      build_progress_steps(@formula)
      render :new
    end
  end

  # PATCH/PUT /formulas/1
  def update
    authorize @formula
    build_multiple_assets

    if @formula.update(formula_params)
      redirect_to @formula, notice: 'Formula was successfully updated.'
    else
      @state_select_options = Formula.state_options
      build_progress_steps(@formula)
      render :edit
    end
  end

  # # DELETE /formulas/1
  # def destroy
  #   @formula.destroy
  #   redirect_to formulas_url, notice: 'Formula was successfully destroyed.'
  # end

  private

  def build_multiple_assets
    base = @formula.formulas_assets.count
    assets = params[:formula].delete(:assets) || []

    assets.each_with_index do |asset, index|
      added_asset = {(base + index).to_s => {"asset" => asset}}
      params[:formula][:formulas_assets_attributes] ||= {}
      params[:formula][:formulas_assets_attributes].merge!(added_asset)
    end
  end

  def build_progress_steps(formula)
    build_steps = policy_scope(ProgressStep.active) -
      policy_scope(formula.progress_steps)
    build_steps.each do |progress_step|
      formula.formulas_progress_steps.build(progress_step: progress_step)
    end
  end

  def params_has_state_condition?
    return false unless params[:q].try(:[], :c).present?
    params[:q][:c].values.any? do |c|
      # any condition attributes include state?
      c[:a].values.any? {|a| a.values.include? 'state'} # &&
      # c[:v].values.any? {|v| v.values.include? 'all'}
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_formula
    @formula = Formula.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def formula_params
    params.require(:formula).permit(policy(Formula).permitted_attributes)
  end
end

app/views/formulas/_form.html.erb
<%= form_for @formula, html: {multipart: true} do |f| %>
  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
  </div>

  <% if @formula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formula.errors.count, "error") %> prohibited this formula from being saved:</h2>

      <ul>
      <% @formula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <a data-toggle="collapse" href="#form_details">Details for <%= @details_title %></a>
    </div>
    <div id='form_details' class="panel-body collapse <%= @default_collapse_state %>">
      <div class="row">
        <div class="col-sm-4">
          <%= f.label :name, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="col-sm-4">
          <%= f.label :code, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :code, class: "form-control" %>
          </div>
        </div>

        <div class="col-sm-4">
          <%= f.label :state, 'Status', class: "control-label" %>
          <div class="controls">
            <%= f.select(:state, @state_select_options, {}, {class: "form-control"}) %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4">
          <%= f.label :priority, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :priority, class: "form-control" %>
          </div>
        </div>

        <div class="col-sm-4">
          <%= f.label :reviewed_by, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :reviewed_by, class: "form-control" %>
          </div>
        </div>

        <div class="col-sm-4">
        <div class="control-group">
          <%= f.label :assets, 'Reference Files', class: 'control-label' %>
          <div class="controls">
            <%= f.fields_for :formulas_assets do |nested_f|%>
              <% if nested_f.object.asset.present? %>
                <%= link_to nested_f.object.asset.original_filename, nested_f.object.asset.url, target: '_blank' %> |
              <% else %>
                <!-- Use HTML5 multiple attribute to enable multiple selection
                     and pass back to controller all files as an array.
                     file_field_tag, since images is not a gallery attribute
                  -->
                <%= file_field_tag "formula[assets][]", id: "formula_assets", type: :file, multiple: true %>
                <!--%= nested_f.file_field :assets[], multiple: true %-->
              <% end %>
            <% end %>
          </div>
        </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4">
          <%= f.label :start_date, class: "control-label" %>
          <div class="controls">
            <%= f.date_select :start_date, use_month_numbers: true, prompt: true, class: "form-control" %>
          </div>
        </div>

        <div class="col-sm-4">
          <%= f.label :requested_by, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :requested_by, class: "form-control" %>
          </div>
        </div>

        <div class="col-sm-4">
          <%= f.label :customer, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :customer, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= f.label :comments, class: "control-label" %>
          <div class="controls">
            <%= f.text_area :comments, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
  <div class="table-responsive">
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>
        <div class="container-fluid">
        <div class="row">
          <div class="col-sm-6">Progress Step</div>
          <div class="col-sm-2">Completed</div>
          <div class="col-sm-3">Completed On</div>
          <div class="col-sm-12"></div>
        </div>
        </div>
        </th>
      </tr>
    </thead>
    <tbody>
    <%= f.fields_for :formulas_progress_steps do |nested_f| %>
      <% if [:create?, :update?].any? {|m| policy(nested_f.object.progress_step).send(m)}  %>
        <tr>
          <td>
          <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6">
              <%= nested_f.hidden_field :progress_step_id %>
              <%= nested_f.label nested_f.object.progress_step.description, class: 'control-label' %>
            </div>
            <div class="col-sm-2"><%= nested_f.check_box :completed, {class: "form-control"}, "true", "false" %></div>
            <div class="col-sm-3"><%= nested_f.date_select :completed_on, use_month_numbers: true, prompt: true, class: "form-control" %></div>
            <div class="col-sm-12"><%= nested_f.text_field :comments, class: "form-control", placeholder: 'Comments...' %></div>
          </div>
          </div>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
  </div>
  </div>
<% end %>

app/views/formulas/edit.html.erb
<h3>
  Editing Formula
  <%= link_to 'Show', @formula, class: 'btn btn-default' %>
  <%= link_to 'Back', formulas_path, class: 'btn btn-default' %>
</h3>

<%= render 'form' %>

app/views/formulas/index.html.erb
<h3>
  New Formula Progress
  <%= link_to 'New Formula', new_formula_path, class: 'btn btn-primary' %>
</h3>

<div class="panel panel-default">
  <div class="panel-heading">
    <a data-toggle="collapse" href="#search_and_sort">Search and Sort</a>
  </div>
  <div id='search_and_sort' class="panel-body collapse">
    <%= search_form_for @search, class: "form-inline" do |f| %>
      <%= f.condition_fields do |c| %>
        <%= render 'search/condition_fields', f: c %>
      <% end %>

      <%= link_to_add_search_field f, :condition %>

      <%= f.sort_fields do |s| %>
        <%= render 'search/sort_fields', f: s %>
      <% end %>

      <%= link_to_add_search_field f, :sort %>
      <br>
      <%= f.submit nil, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Formula Name</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @formulas.each do |formula| %>
      <tr>
        <td><%= link_to formula.name, formula %></td>
        <td><%= formula.priority %></td>
        <td><%= formula.state %></td>
        <td><%#= link_to 'Show', formula, class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_formula_path(formula), class: 'btn btn-default btn-xs' %></td>
        <td><%#= link_to 'Destroy', formula, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/formulas/new.html.erb
<h3>
  New Formula
  <%= link_to 'Back', formulas_path, class: 'btn btn-default' %>
</h3>

<%= render 'form' %>

app/views/formulas/show.html.erb
<h3>
  Formula
  <%= link_to 'Edit', edit_formula_path(@formula), class: 'btn btn-default' %>
  <%= link_to 'Back', formulas_path, class: 'btn btn-default' %>
</h3>

<p>
  <strong>Name:</strong>
  <%= @formula.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @formula.code %>
</p>

<p>
  <strong>Status:</strong>
  <%= @formula.state %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @formula.priority %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @formula.comments %>
</p>

<p>
  <strong>Reviewed by:</strong>
  <%= @formula.reviewed_by %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @formula.start_date.try(:to_date) %>
</p>

<p>
  <strong>Requested by:</strong>
  <%= @formula.requested_by %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @formula.customer %>
</p>

<p>
  <strong>Reference Files:</strong>
  <% @formula.formulas_assets.each do |formulas_asset| %>
    <%= link_to formulas_asset.asset.original_filename, formulas_asset.asset.url, target: '_blank' %> |
  <% end %>
</p>

<table class="table table-striped table-condensed table-bordered table-responsive">
  <thead>
    <tr>
      <th>
      <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">Progress Step</div>
        <div class="col-sm-2">Completed</div>
        <div class="col-sm-3">Completed On</div>
        <div class="col-sm-12">Comments</div>
      </div>
      </div>
      </th>
    </tr>
  </thead>
  <tbody>
  <% @formula.formulas_progress_steps.each do |formulas_progress_step| %>
    <tr>
      <td>
      <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6"><%= formulas_progress_step.progress_step.description %></div>
        <div class="col-sm-2"><%= check_box_tag :completed, '1', formulas_progress_step.completed, disabled: true%></div>
        <div class="col-sm-3"><%= formulas_progress_step.completed_on.try(:to_date) %></div>
        <div class="col-sm-12"><%= formulas_progress_step.comments %></div>
      </div>
      </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>